### PR TITLE
Add some docs for dependencies and running.

### PR DESCRIPTION
**Pull request by henning**
After looking up these things for myself, I added these docs:

* install command for Ubuntu/Debian
* hint on where to find hylia
* describe option -n/--nofork

### CODE REVIEW

**Comment by falkTX** [comment]
Thanks, but `fftw-dev` is not really a package.
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=sourcenames&keywords=fftw-dev lists no results.
It should say `libfftw3-dev` instead.

**Comment by henning** [comment]
OK if you are sure this is the better package that should be used I can change it.

But the reason why his search yields no results is probably because the link appears to look for source package names only.

There it is:

* https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=fftw-dev
* https://packages.ubuntu.com/search?keywords=fftw-dev&searchon=names&suite=impish&section=all

**Comment by henning** [comment]
Ok I see in the Makefile it's checking for fftw3 things, and fftw-dev would only pull in fftw2 (even without dev).
There is also fftw3-dev but I added libftw3-dev as told.

**Comment by falkTX** [comment]
Applied as bf6dfc90e2c0b1719c54c41a858d49e9c0c7af5d with some minor wording tweaks, thanks!

**Pull request closed without merging**
